### PR TITLE
doc/rustc: fill out target platform-support docs

### PR DESCRIPTION
**Pull request by adamgreig**
Adds maintainers and other information for bare-metal MSP430, RISC-V RV32I/IMC/IMAC, and thumbv{6,7,8} targets.

* thumbv7em-none-eabihf, thumbv7em-none-eabi now both point to thumbv7m-none-eabi as the relevant documentation is shared
* similarly thumbv8m.main-none-eabi and thumbv8m.main-none-eabihf both point to thumbv8m.base-none-eabi
* similarly riscv32i-unknown-none-elf, riscv32imc-unknown-none-elf both point to riscv32imac-unknown-none-elf
* the riscv32im-unknown-none-elf file is left untouched for now as it already has a maintainer and is tier 3 (the rest are tier 2), but in the future a separate PR to upstream could promote it to tier 2 and merge its platform support file with the other three targets
* most of these maintainers are rust-embedded working group teams, so represent a few developers

cc https://github.com/rust-embedded/wg/issues/704

### CODE REVIEW

**Comment by adamgreig** [comment]
Hi @davidtwco, just wanted to check if you'd seen the PR and had any feedback!

**Comment by davidtwco** [comment]
> Hi @davidtwco, just wanted to check if you'd seen the PR and had any feedback!

:wave: I have, just a bit behind - this looks good, and I'll incorporate it once I've got some time to look at the target tier work :)

**Comment by MabezDev** [comment]
I have a need for the imafc target, and I wasn't allowed to grandfather it in, so I've copied much of the work here into that PR: https://github.com/rust-lang/rust/pull/117874, just as an FYI

**Comment by adamgreig** [comment]
It looks like some of these changes are now obsoleted by either https://github.com/rust-lang/rust/pull/117874 (above, for risc-v) or https://github.com/rust-lang/rust/pull/119102 (for the thumb targets) and the upstream PR is closed (https://github.com/rust-lang/rust/pull/116004) so I'll close this too. Hopefully the other updates can make their way into rust-lang one way or another.

**Pull request closed without merging**
